/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'prakash' at '10/4/16 11:56 PM' with Gradle 2.9
 *
 * @author prakash, @date 10/4/16 11:56 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
